Rachael-Kim/rc0821-code-solutions

html-skeleton/.npmrc
html-skeleton/index.html

completed html-skeleton exercise: Rachael Kim

---

html-syntax/.npmrc
html-syntax/index.html

completed html-syntax exercise: Rachael Kim

---

html-block-and-inline/.npmrc
html-block-and-inline/index.html

completed html-block-and-inline exercise: Rachael Kim

---

html-lists/.npmrc
html-lists/index.html

completed html-lists exercise: Rachael Kim

---

html-links/.npmrc
html-links/index.html

html-links: Rachael Kim 

---

html-forms/.npmrc
html-forms/index.html

html-forms completed

---

html-tables/.npmrc
html-tables/index.html

completed html tables exercise: Rachael Kim

---

css-box-model/.npmrc
css-box-model/index.html
css-box-model/styles.css

css-box-model completed: Rachael Kim

---

css-pseudo-classes/.npmrc
css-pseudo-classes/index.html
css-pseudo-classes/styles.css

css-pseudo-classes: Rachael Kim

---

css-fonts/.npmrc
css-fonts/.stylelintrc
css-fonts/index.html
css-fonts/styles.css

completed css-fonts: Rachael Kim

---

javascript-operators-and-expressions/.eslintrc
javascript-operators-and-expressions/.npmrc
javascript-operators-and-expressions/index.html
javascript-operators-and-expressions/main.js

completed js operators and expressions

---

javascript-objects/.eslintrc
javascript-objects/.npmrc
javascript-objects/index.html
javascript-objects/main.js

javascript objects completed

---

javascript-arrays/.eslintrc
javascript-arrays/.npmrc
javascript-arrays/index.html
javascript-arrays/main.js

javascript-arrays completed

---

object-manipulation-1/.eslintrc
object-manipulation-1/.npmrc
object-manipulation-1/index.html
object-manipulation-1/src/ban-methods.js
object-manipulation-1/src/get-keys.js
object-manipulation-1/src/get-keys.test.js
object-manipulation-1/src/get-value.js
object-manipulation-1/src/get-value.test.js
object-manipulation-1/src/get-values.js
object-manipulation-1/src/get-values.test.js
object-manipulation-1/src/set-value.js
object-manipulation-1/src/set-value.test.js
object-manipulation-1/src/to-object.js
object-manipulation-1/src/to-object.test.js

object-1 completed

---

array-manipulation-2/.eslintrc
array-manipulation-2/.npmrc
array-manipulation-2/index.html
array-manipulation-2/src/ban-methods.js
array-manipulation-2/src/chunk.js
array-manipulation-2/src/chunk.test.js
array-manipulation-2/src/drop-right.js
array-manipulation-2/src/drop-right.test.js
array-manipulation-2/src/drop.js
array-manipulation-2/src/drop.test.js
array-manipulation-2/src/includes.js
array-manipulation-2/src/includes.test.js
array-manipulation-2/src/take-right.js
array-manipulation-2/src/take-right.test.js
array-manipulation-2/src/take.js
array-manipulation-2/src/take.test.js

array-manipulation-2 completed

---

dom-querying/.eslintrc
dom-querying/.npmrc
dom-querying/index.html
dom-querying/main.js

dom-querying completed

---

dom-events/.eslintrc
dom-events/.npmrc
dom-events/buttons.html
dom-events/buttons.js
dom-events/document.html
dom-events/document.js
dom-events/styles.css

dom-events completed

---

dom-manipulation/.npmrc
dom-manipulation/index.html
dom-manipulation/main.js
dom-manipulation/styles.css

dom-manipulation completed

---

javascript-light-bulb/.npmrc
javascript-light-bulb/index.html
javascript-light-bulb/main.js
javascript-light-bulb/styles.css

light-bulb completed

---

javascript-typing-tutor/.npmrc
javascript-typing-tutor/index.html
javascript-typing-tutor/main.js
javascript-typing-tutor/styles.css

javascript-typing-tutor completed

---

javascript-forms/.eslintrc
javascript-forms/.npmrc
javascript-forms/form-events.html
javascript-forms/form-events.js
javascript-forms/form-values.html
javascript-forms/form-values.js
javascript-forms/styles.css

javascript-forms completed

---

javascript-and-json/.eslintrc
javascript-and-json/.npmrc
javascript-and-json/index.html
javascript-and-json/main.js

js-json completed

---

javascript-local-storage/.eslintrc
javascript-local-storage/.npmrc
javascript-local-storage/data.js
javascript-local-storage/index.html
javascript-local-storage/main.js
javascript-local-storage/styles.css

completed js local storage

---

object-manipulation-3/.eslintrc
object-manipulation-3/.npmrc
object-manipulation-3/index.html
object-manipulation-3/main.js

object3 completed

---

javascript-constructors/.eslintrc
javascript-constructors/.npmrc
javascript-constructors/example-constructor.html
javascript-constructors/example-constructor.js
javascript-constructors/index.html
javascript-constructors/new-objects.html
javascript-constructors/new-objects.js
javascript-constructors/stopwatch.html
javascript-constructors/stopwatch.js
javascript-constructors/student.js
javascript-constructors/student.test.js
javascript-constructors/test.html

completed js constructors

---

javascript-bank/.eslintrc
javascript-bank/.npmrc
javascript-bank/account.js
javascript-bank/account.test.js
javascript-bank/bank.js
javascript-bank/bank.test.js
javascript-bank/index.html
javascript-bank/test.html
javascript-bank/transaction.js
javascript-bank/transaction.test.js

js bank completed

---

javascript-timers/.npmrc
javascript-timers/interval.html
javascript-timers/interval.js
javascript-timers/timeout.html
javascript-timers/timeout.js

timers completed

---

javascript-ajax/.eslintrc
javascript-ajax/.npmrc
javascript-ajax/pokemon.html
javascript-ajax/pokemon.js
javascript-ajax/users.html
javascript-ajax/users.js

completed ajax

---

es6-const-let/.eslintrc
es6-const-let/.npmrc
es6-const-let/index.html

completed es6 exercise

---

es6-template-literals/.eslintrc
es6-template-literals/.npmrc
es6-template-literals/index.html

completed es6 template

---

es6-destructuring/.eslintrc
es6-destructuring/.npmrc
es6-destructuring/index.html
es6-destructuring/main.js

destructuring completed

---

node-module-system/.eslintrc
node-module-system/.npmrc
node-module-system/a-wrapped-module.js

completed node module system

---

the-event-loop/.eslintrc
the-event-loop/.npmrc
the-event-loop/interval.js
the-event-loop/timeout.js

completed event-loop-exercise

---

express-post-json/.npmrc
express-post-json/index.js
express-post-json/package.json

completed express post
